services:
  db:
    build: ./docker/postgres
    image: postgres-image
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - movie-api_net

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - fast-api
    ports:
      - 80:80
    networks:
      - movie-api_net

  fast-api:
    build: ./src
    image: fastapi-image
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - movie-api_net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    restart: on-failure
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - movie-api_net

  redis:
    restart: unless-stopped
    expose:
      - 6379
    image: redis:6.2.5
    volumes:
      - redis_data:/data
    networks:
      - movie-api_net

  etl:
    build: ./docker/etl
    image: etl-image
    env_file:
      - .env
    depends_on:
      - db
      - es
    networks:
      - movie-api_net

networks:
    movie-api_net:
        name: movie-api_net
        driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  es_data:
    name: es_data
  redis_data:
    name: redis_data