FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.1

WORKDIR /usr/share/elasticsearch

COPY . .

#RUN tar -xvaf ./es_test_data.tar.gz \
#    && rm ./es_test_data.tar.gz

#ENTRYPOINT ["/tini", "--", "/usr/local/bin/docker-entrypoint.sh", "eswrapper"]
